## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of 'NumPy, focusing on arrays and vectorized operations'.

In [3]:
import numpy as np
# create array using numpy
#create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
#1D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) #here, 1 row and  5 col

array([[1, 2, 3, 4, 5]])

In [5]:
# 2D array
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

shape, reshape, arange, ones, eye

In [5]:
# attributes of NumPy Array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape) #(2,3)
print("Number of Dimension:", arr.size) ##output 2
print("Size (number of elements):",arr.size) #output 6
print("Data Type:",arr.dtype) # int 64
print("Item size (in bytes):", arr.itemsize) #8

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of Dimension: 6
Size (number of elements): 6
Data Type: int64
Item size (in bytes): 8


In [18]:
##NumPy Vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition
print("Addition:", arr1+arr2)

#element wise subtraction
print('Subtraction:', arr1-arr2)

#element wise Multiplication
print('Multiplication:', arr1*arr2)

#element wise division
print('Division:', arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [6]:
# Universal Function
arr = np.array([2,3,4,5,6])

#sqrt
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [30]:
## array slicing and indexing
import numpy as nb
arry = nb.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print("Array: \n", arry)



Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
print(arry[0][0])
print(arry[0:2, 2:])
print(arry[1:,1:3])

1
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [32]:
print(arry[1:,2:])

[[ 7  8]
 [11 12]]


In [48]:
## modify the array element
arry[0,0] =1
print(arry)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [51]:
arry[1:]= 100
print(arry)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [68]:
#Statistical concepts - Normalization
# to have a mean of 0 and standard deviation
import numpy as np
data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
print(mean)
std_div = np.std(data)
print(std_div)

#normalize the data
nor_data = (data - mean)/std_div
print(f'Normalized Data: {nor_data}')

3.0
1.4142135623730951
Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [72]:
import numpy as np

data = np.array([1,2,3,4,5,6,7,8,9,10])

#mean
mean = np.mean(data)
print("Mean: ",mean)

#median
median = np.median(data)
print("Median: ",median)

#standard deviation
std_div = np.std(data)
print("Standard Deviation: ", std_div)

#variance
variance = np.var(data)
print("Variance: ",variance)

Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [79]:
# logical operation
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])