In [2]:
import numpy as np

In [5]:
#create array using numpy
#Create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
#2d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##attributes
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("Shape: ", arr.shape)
print("No of Dimensions: ",arr.ndim)
print("Size(number of elements): ",arr.size)
print("Data Type: ", arr.dtype)
print("Item Size (in bytes): ", arr.itemsize)


Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
No of Dimensions:  2
Size(number of elements):  6
Data Type:  int64
Item Size (in bytes):  8


In [31]:
#numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## element wise addition
print("Addition:", arr1+arr2)

## element wise subtraction
print("Subtraction:", arr1-arr2)

## element wise Multiplication
print("Multiplication:", arr1*arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]


In [33]:
#universal function
arr = np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [43]:
## array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array:\n',arr)

arr[0][1]


Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


np.int64(2)

In [48]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [ ]:
## modify array elements
arr